---
# /roles/common/xorg/tasks/main.yml

- name: Install xorg display server
  become: yes
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - 'xorg'
    - 'curl'
    - 'wget'
    - 'ncdu'
    - 'bmon'
    - 'screen'