---
- name: local installation
  hosts: localhost
  become: true
  roles:
    - role: common/timezone
      tags:
        - always
    - role: common
      tags:
        - always
   - role: common/xorg
     tags:
       - test