---
- name: local installation
  hosts: localhost
  become: true
  roles:
    - role: common/timezone
      tags:
        - min
        - dev
        - full
    - role: common
      tags:
        - min
        - dev
        - full
   - role: common/xorg
     tags:
       - test