---
- name: local installation
  hosts: localhost
  become: true
  roles:
    - role: common/timezone
      tags:
        - test
    - role: common
      tags:
        - min
        - dev
        - all
   # - role: common/xorg
   #   tags:
   #     - min
   #     - dev
   #     - all