---
# /roles/common/tasks/main.yml

- name: Update repositories
  become: yes
  apt:
    update_cache: yes

- name: Install basic packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'htop'
    - 'curl'
    - 'wget'
    - 'ncdu'
    - 'bmon'
    - 'screen'